### ISSUE TITLE
第一周-学习如何通过Github进行多人协作

### ISSUE THREAD

**Issue by ElvisNam** [FE-boom/learngit#7]
### 学习利用Github进行多人协作
1.在此之前，你需要了解Github个人界面的基本操作，如：Repositories、Fork等。
2.在Github中，我们主要利用其Organizations、Team等方式进行多人协作，具体使用方式如下：

- 在个人页面点击Organizations下的组织图标进入组织页面：
![image1](https://cloud.githubusercontent.com/assets/12369819/20297111/c33b142e-ab49-11e6-9872-d200654faddc.png)

- 进入组织页面后可看见界面上方一排菜单：
![image2](https://cloud.githubusercontent.com/assets/12369819/20297165/0cf8c61a-ab4a-11e6-95b5-d60eed9fa9e7.png)
其中：
**Repositories**：表示代码项目/远程仓库。后期的学习中，我们将代码练习上传至相应的项目之中，方便查看以及掌控进度。
People：该公司/组织下的成员。
Teams：公司/组织下细分的团队/部门。
**Projects**：项目安排。今后所有任务/项目将在此发布（防止QQ群内信息错失），同时其带来的可视化进度安排，方便大家及时跟进完成，请大家务必定期访问查看任务安排。

- Projects管理说明：
![image4](https://cloud.githubusercontent.com/assets/12369819/20297711/d8ee3c3a-ab4c-11e6-84f9-ea99cf56ca63.png)
进入Task项目，可看到3个任务条例。
其中：
TODO：作为即将安排的任务，可用于进度较快的同学提前完成。
In Progress：作为当前安排的任务，应及时完成。
Finish：每个任务都有其`最迟完成时间`，若超过改时间，任务将拖至此条例下，同时关闭上传权限。
**请注意：Projects下的任务添加、删除等对于组员都是开放权限的，因此请不要随意改变任务进度、添加删除任务等**

- Issues：
每个仓库项目下都有一个Issues菜单栏，可用于对项目内代码提bug、发布需求、安排任务等。同时，在我们的Projects中点击每一个任务卡片都将跳转至指定Issues，用于对任务进行详细说明、成员描述问题等。
** 请注意：对于完成该任务的同学，请务必在相应Issues下通过留言的方式回复“”已完成“”，已方便任务安排者及时更新、发布、关闭任务。（请每位朋友遵守此规定） **

***
#### 最后请注意：
本学习小组未收取同时不会收取各位任何费用。组织者希望利用自己的资源帮助大家走上**前端**这条道路，同时尽可能帮助你们少走弯路。因此，也请大家尊重组织者的劳动成果，及时完成练习。

据了解，本学习小组中至少有3人是完全打算靠前端作为今后的职业方向的，因此请这些朋友们尽量多花点时间学习，尽量赶在`预期完成时间`内完成任务安排。其他朋友可能目前暂无该职业安排，通过爱好或想了解前端而加入小组的，我们也热情欢迎，同时也请赶在`最迟完成时间`内完成。

本学习小组只针对前端，只针对前端，只针对前端！！WEB前端、H5前端！！
走错路想学后端、原生IOS、原生Android的想在回去还来得及....

**Comment by Liu-yan** [comment]
已完成

**Comment by DreamHyu** [comment]
已完成

**Comment by songyuanxianha** [comment]
已完成

**Comment by sliop** [comment]
已完成
